blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Diobyte/USBPowerManagement-AutoDisable/discussions
    about: Ask questions and discuss with the community
